### ISSUE TITLE
no pv after deploy: No resources found

### ISSUE THREAD

**Issue by kandeshvari** [kubernetes-sigs/sig-storage-local-static-provisioner#105]
I just tried to deploy provisioner via documentation steps and via apply https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/local-dind/local-volume-provisioner.yaml but got error "No resources found" from `kubectl get pv -A`. 

local-static-provisioner pod says all is ok:
```
I0529 12:39:15.180218       1 common.go:292] StorageClass "local-storage" configured with MountDir "/media/disk/local-storage", HostDir "/media/disk/local-storage", BlockCleanerCommand ["/scripts/quick_reset.sh"]
I0529 12:39:15.180348       1 main.go:60] Loaded configuration: {StorageClassConfig:map[local-storage:{HostDir:/media/disk/local-storage MountDir:/media/disk/local-storage BlockCleanerCommand:[/scripts/quick_reset.sh]}] NodeLabelsForPV:[kubernetes.io/hostname] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false}
I0529 12:39:15.180387       1 main.go:61] Ready to run...
I0529 12:39:15.180586       1 common.go:352] Creating client using in-cluster config
I0529 12:39:15.194563       1 main.go:82] Starting controller
I0529 12:39:15.194599       1 main.go:96] Starting metrics server at :8080
I0529 12:39:15.194956       1 controller.go:45] Initializing volume cache
I0529 12:39:15.397857       1 controller.go:108] Controller started
```

I confused by `provisioner: "kubernetes.io/no-provisioner"` in StorageClass definition. Is it correct?

Here is my config. What is wrong?
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "local-storage"
provisioner: "kubernetes.io/no-provisioner"
volumeBindingMode: "WaitForFirstConsumer"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: kube-system
data:
  nodeLabelsForPV: |
    - kubernetes.io/hostname
  storageClassMap: |
    local-storage:
      hostDir: /media/disk/local-storage
      mountDir: /media/disk/local-storage

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: kube-system
  labels:
    app: local-volume-provisioner
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-storage-admin
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:v2.2.0"
          name: provisioner
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: "quay.io/external_storage/local-volume-provisioner:v2.2.0"
          volumeMounts:
            - mountPath: /etc/provisioner/config
              name: provisioner-config
              readOnly: true
            # mounting /dev in DinD environment would fail
            # - mountPath: /dev
            #   name: provisioner-dev
            - mountPath: /media/disk/local-storage
              name: local-disks
              mountPropagation: "HostToContainer"
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        # - name: provisioner-dev
        #   hostPath:
        #     path: /dev
        - name: local-disks
          hostPath:
            path: /media/disk/local-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-pv-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-storage-provisioner-node-clusterrole
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-node-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: local-storage-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
```
