### ISSUE TITLE
[help]multpile pvs on one node

### ISSUE THREAD

**Issue by w548544375** [kubernetes-sigs/sig-storage-local-static-provisioner#158]
hi,thanks for your time!
i am trying to build a mysql master-slave demo on my mac machine with in minikuber (v.1.5.2).
**First Step** 
i had create three direct directories master01,slave01,slave02 in minikube vm.
`$ ls /mnt/ `
`master01  slave01  slave02  vda1`
**Second Step**
there are my k8s files.

1. sc.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```
2. pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master01
  labels:
    pv: master01
spec:
  capacity:
    storage: 2Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/master01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-slave01
  labels:
    pv: slave01
spec:
  capacity:
    storage: 2Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/slave01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-slave02
  labels:
    pv: slave02
spec:
  capacity:
    storage: 2Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/slave02
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
```
3.pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master01-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      pv: master01

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slave01-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      pv: slave01
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slave02-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      pv: slave02
```
4. mysql-deployment.yaml
```
# master deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master01-deployment
  labels:
    deploy: mysql-master01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master01
  template:
    metadata:
      labels:
        app: mysql-master01
    spec:
      volumes:
      - name: master01-volume
        persistentVolumeClaim:
          claimName: master01-pvc
      - name: common-config
        configMap:
          name: mysql-config
          items:
          - key: my.cnf
            path: mysqld.cnf
      - name: master-config
        configMap:
          name: mysql-config
          items:
          - key: master01.cnf
            path: docker.cnf
      containers:
      - name: mysql-master01
        image: mysql:master
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: master
        - name: MYSQL_SLAVE_USER
          value: slave
        - name: MYSQL_SLAVE_PASSWORD
          value: slavemustusepassword
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: master01-volume
        - mountPath: /etc/mysql/mysql.conf.d/
          name: common-config
        - mountPath: /etc/mysql/conf.d/
          name: master-config
        ports:
        - containerPort: 3306        

---

# slave01 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave01-deployment
  labels:
    deploy: mysql-slave01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave01
  template:
    metadata:
      labels:
        app: mysql-slave01
    spec:
      volumes:
      - name: slave01-volume
        persistentVolumeClaim:
          claimName: slave01-pvc
      - name: common-config
        configMap:
          name: mysql-config
          items:
          - key: my.cnf
            path: mysqld.cnf
      - name: slave01-config
        configMap:
          name: mysql-config
          items:
          - key: slave01.cnf
            path: docker.cnf
      containers:
      - name: mysql-slave01
        image: mysql:slave
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: slave01
        - name: MYSQL_SLAVE_USER
          value: slave
        - name: MYSQL_SLAVE_PASSWORD
          value: slavemustusepassword
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: slave01-volume
        - mountPath: /etc/mysql/mysql.conf.d/
          name: common-config
        - mountPath: /etc/mysql/conf.d/
          name: slave01-config
        # ports:
        # - containerPort: 3306  

---

# slave02 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave02-deployment
  labels:
    deploy: mysql-slave02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave02
  template:
    metadata:
      labels:
        app: mysql-slave02
    spec:
      volumes:
      - name: slave02-volume
        persistentVolumeClaim:
          claimName: slave02-pvc
      - name: common-config
        configMap:
          name: mysql-config
          items:
          - key: my.cnf
            path: mysqld.cnf
      - name: slave02-config
        configMap:
          name: mysql-config
          items:
          - key: slave02.cnf
            path: docker.cnf
      containers:
      - name: mysql-slave02
        image: mysql:slave
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: slave02
        - name: MYSQL_SLAVE_USER
          value: slave
        - name: MYSQL_SLAVE_PASSWORD
          value: slavemustusepassword
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: slave02-volume
        - mountPath: /etc/mysql/mysql.conf.d/
          name: common-config
        - mountPath: /etc/mysql/conf.d/
          name: slave02-config
        ports:
        - containerPort: 3306  
```
5. mysql-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  # resourceVersion: "1.0"
data:
  my.cnf: |
    [mysqld]
    datadir = /var/lib/mysql
    log-bin = mysql-bin
  master01.cnf: |
    [mysqld]
    server-id=1 
  slave01.cnf: |
    [mysqld]
    server-id=2
  slave02.cnf: |
    [mysqld]
    server-id=3
```
 i am trying to deploy one mysql it works
```
weiguang@iMac standalone % kubectl get deployments
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
mysql-master01-deployment   1/1     1            1           40m
weiguang@iMac standalone % kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
mysql-master01-deployment-5cc566496-scm9v   1/1     Running   3          41m
weiguang@iMac standalone % 
```
but when i trying to deploy slave01 to k8s ,both of the pods got error.
```
weiguang@iMac standalone % kubectl apply -f mysql-deployment.yaml -l deploy=mysql-slave01
deployment.apps/mysql-slave01-deployment created
weiguang@iMac standalone % kubectl get pods
NAME                                        READY   STATUS   RESTARTS   AGE
mysql-master01-deployment-5cc566496-scm9v   0/1     Error    5          44m
mysql-slave01-deployment-64cd7c96d8-gksl4   0/1     Error    1          39s
```
then i had tried deploy slave01 without mount pvc, both pods running。
```
weiguang@iMac standalone % kubectl get pv
NAME          CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                  STORAGECLASS    REASON   AGE
pv-master01   2Gi        RWO            Delete           Bound       default/master01-pvc   local-storage            53m
pv-slave01    2Gi        RWO            Delete           Bound       default/slave01-pvc    local-storage            53m
pv-slave02    2Gi        RWO            Delete           Available                          local-storage            53m
weiguang@iMac standalone % kubectl get pvc
NAME           STATUS    VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS    AGE
master01-pvc   Bound     pv-master01   2Gi        RWO            local-storage   53m
slave01-pvc    Bound     pv-slave01    2Gi        RWO            local-storage   53m
slave02-pvc    Pending                                           local-storage   53m
```

could anyone do me a favor,plz tell me what wrong with my pvs or pvcs?
