### ISSUE TITLE
PersistentVolume not being created

### ISSUE THREAD

**Issue by s-u-m-e** [kubernetes-sigs/sig-storage-local-static-provisioner#163]
I'm trying to get the provisioner to work on my 1 node ubuntu kubernetes cluster. What am I missing?

I followed the instructions [here](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md) and the [Operations readme](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/operations.md) 
`/etc/fstab` has `UUID=4ca52b7d-87ac-405c-bb72-604492ee83a0 /home/sume/storage  ext4 defaults 0 2`

I have applied the following configs.
```
---
# Source: provisioner/templates/provisioner.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: default
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3
data:
  storageClassMap: |
    local-storage:
       hostDir: /home/sume/storage
       mountDir: /home/sume/storage
       volumeMode: Filesystem
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: default
  labels:
    app: local-volume-provisioner
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-storage-admin
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:v2.3.3"
          name: provisioner
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: "quay.io/external_storage/local-volume-provisioner:v2.3.3"
          volumeMounts:
            - mountPath: /etc/provisioner/config
              name: provisioner-config
              readOnly: true
            - mountPath: /dev
              name: provisioner-dev
            - mountPath: /home/sume/storage
              name: local-storage
              mountPropagation: "HostToContainer"
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: local-storage
          hostPath:
            path: /home/sume/storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
# Source: provisioner/templates/provisioner-service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
  namespace: default
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3

---
# Source: provisioner/templates/provisioner-cluster-role-binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-pv-binding
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-storage-provisioner-node-clusterrole
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-node-binding
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.3
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: local-storage-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
```
The local provisioner pod is not showing any errors

```➜  storage kubectl logs -f local-volume-provisioner-f49b4
I1225 17:12:33.424147       1 common.go:334] StorageClass "local-storage" configured with MountDir "/home/sume/storage", HostDir "/home/sume/storage", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
I1225 17:12:33.424215       1 main.go:63] Loaded configuration: {StorageClassConfig:map[local-storage:{HostDir:/home/sume/storage MountDir:/home/sume/storage BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:}] NodeLabelsForPV:[] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false LabelsForPV:map[] SetPVOwnerRef:false}
I1225 17:12:33.424268       1 main.go:64] Ready to run...
I1225 17:12:33.424490       1 common.go:396] Creating client using in-cluster config
I1225 17:12:33.437169       1 main.go:85] Starting controller
I1225 17:12:33.437193       1 main.go:101] Starting metrics server at :8080
I1225 17:12:33.437263       1 controller.go:45] Initializing volume cache
I1225 17:12:33.637985       1 controller.go:108] Controller started
```
But I don't see any persistent volumes being created.
```
➜  storage kubectl get pv  --all-namespaces
No resources found
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Also, not sure if this is relevant but I have the my device mounted under `/home/sume/storage` and when I created a folder under storage I get the following errors from local-volume-provisioner
`...       1 discovery.go:301] Path "/home/sume/storage/test" is not an actual mountpoint`
