### ISSUE TITLE
Local block devices as a volume source, with partitioning and fs formatting

### ISSUE THREAD

**Issue by rohantmp** [kubernetes-sigs/sig-storage-local-static-provisioner#173]
I see partitioning in the planned Future Feature's section of the Readme.

Is there any development planned in this area?

**Comment by rohantmp** [comment]
CC @leseb

**Comment by cofyc** [comment]
sorry, we don't any plan for this right now. there are many ways to prepare disks on the host. as @msau42 suggested [here](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/167#issuecomment-584236113), using 1) init container or 2) daemonset is recommended.

btw, as for fs formatting, I would recommend leveraging block volume formatting features.

**Comment by andyzhangx** [comment]
Hi @cofyc, I see [doc](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/97900174eb6516ca98aeacc6c7e543bf763a4b29#112-beta) said 

 - 1.12: Beta
Added support for automatically formatting a filesystem on the given block device in localVolumeSource.path

so it formatting supported or not? if supported, how to set? and I don't find any formatting code in this sig-storage-local-static-provisioner repo, not sure whether it's really supported, thanks.

**Comment by andyzhangx** [comment]
Update:
ok, i see formatting is already supported by local-persistent-volumes: https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

**Comment by andyzhangx** [comment]
question is how can I format this block device, even if I set like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: default
data:
  storageClassMap: |
    fast-disks:
       hostDir: /mnt/fast-disks
       mountDir:  /mnt/fast-disks
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: ext4
```

And I still get a `volumeMode: Block` pv, and I can only use raw block device for that pv.
```yaml
# k get pv local-pv-9042a3d7 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-9042a3d7
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1788Gi
  local:
    path: /mnt/fast-disks/nvme0n1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - aks-agentpool-39784301-0
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-disks
  volumeMode: Block
status:
  phase: Available
```

**Comment by cofyc** [comment]
hi, this is a little misleading. [This doc](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/97900174eb6516ca98aeacc6c7e543bf763a4b29#k8s-feature-status) lists the feature status of each Kubernetes version. It's unrelated to provisioner project.

Since 1.12, Block Local PV `volumeMode: Block` can be consumed by Kubernetes. If you don't use block PV as a raw block volume source, it's not necessary to pre-format the underlying block device. The kubelet will format it before mounting it into containers.

**Comment by andyzhangx** [comment]
> hi, this is a little misleading. [This doc](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/97900174eb6516ca98aeacc6c7e543bf763a4b29#k8s-feature-status) lists the feature status of each Kubernetes version. It's unrelated to provisioner project.
> 
> Since 1.12, Block Local PV `volumeMode: Block` can be consumed by Kubernetes. If you don't use block PV as a raw block volume source, it's not necessary to pre-format the underlying block device. The kubelet will format it before mounting it into containers.

hi @cofyc the point is if I use this provisioner driver, I will get `volumeMode: Block` PV for new disk, how can I use it for `volumeMode: Filesystem` pvc and pod? It looks like I need to run a daemonset to format disk first, and then could get `volumeMode: Filesystem` PV for new disk.

**Comment by cofyc** [comment]
this project does not support preparing disks automatically yet. this is because there are too many possibilities here (raid/lvm, partition, etc.). I had thought about it (see my [old proposal](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/103/files)) but don't have enough time to continue. In most cases, users can write a simple shell script in init container to do their specific tasks.

I think it's good to have a solution in this phase.

**Comment by andyzhangx** [comment]
Thanks for the clarification @cofyc , I agree, there are two many options. And is it possible to only implement format functionality(one disk pv for one new disk), that could be a small change, I have already verified it should work, we only need to add field `spec.local.fsType`, and set block device `/dev/xxx` as `volumeMode: Filesystem` in the PV, by  that way, we don't need to workaround(init container or daemonset).  The format would happen in the pod mounting process.

I could do the code change if you agree with this proposal. Thanks.

Below is my experiment on AKS, it should work on other cloud too.
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: local-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1788Gi
  local:
    path: /dev/nvme0n1
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - aks-agentpool-39784301-0
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-disks
status:
  phase: Available
```

```console
# df -h
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/nvme0n1    1.8T   68M  1.8T   1% /fast
/dev/sda1        97G   12G   86G  12% /etc/hosts
...
```
