### ISSUE TITLE
Provisioner Configuration to create both Block and Filesystem PVs for one StorageClass

### ISSUE THREAD

**Issue by skaegi** [kubernetes-sigs/sig-storage-local-static-provisioner#226]
Currently the PVs created per storageClassMap entry have to decide which `volumeMode` to use. It would be good if the provisioner configuration provided a way to create both Block and Filesystem PVs for the same StorageClass.

**Comment by skaegi** [comment]
Perhaps if there was a `storageClassMap.[storageClassName].setPVStorageClass` field I could then do something like...
```
storageClassMap:
  local-storage:
    ...
    volumeMode: FileSystem
  local-storage-block:
    ...
    volumeMode: Block
    setPVStorageClass: local-storage
```
