### ISSUE TITLE
Could this sig support multiple mountPath?

### ISSUE THREAD

**Issue by f7753** [kubernetes-sigs/sig-storage-local-static-provisioner#227]
My generated config file is as below:
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-provisioner
  namespace: default
  labels:
    helm.sh/chart: provisioner-3.0.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: my
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: provisioner
      app.kubernetes.io/instance: my
  template:
    metadata:
      labels:
        app.kubernetes.io/name: provisioner
        app.kubernetes.io/instance: my
      annotations:
        checksum/config: 1be9e8c9b0008094e8ed42f3be311614ea1437cab686013d81ade8bdca2337ec
    spec:
      serviceAccountName: my-provisioner
      priorityClassName: system-node-critical
      nodeSelector:
        
        local-pv: present
        
      containers:
        - name: provisioner
          image: quay.io/external_storage/local-volume-provisioner:v2.3.4
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: quay.io/external_storage/local-volume-provisioner:v2.3.4
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: fast-disks
              mountPath: [/data1 /data2 /data3 /data4]
              mountPropagation: HostToContainer
      volumes:
        - name: provisioner-config
          configMap:
            name: my-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: fast-disks
          hostPath:
            path: [/data1 /data2 /data3 /data4]
```

when I use kubectl to deploy this daemonset to the  cluster, it occurred to:
```bash
unable to recognize "local-volume-provisioner.generated.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
error validating "local-volume-provisioner.generated.yaml": error validating data: ValidationError(DaemonSet.spec.template.spec.volumes[2].hostPath.path): invalid type for io.k8s.api.core.v1.HostPathVolumeSource.path: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

Are there any method to support multi-path of disks?
Thanks a lot.
