### ISSUE TITLE
Specify labelsForPV inside entries in the storageClassMap

### ISSUE THREAD

**Issue by St0rmingBr4in** [kubernetes-sigs/sig-storage-local-static-provisioner#259]
**Is your feature request related to a problem?/Why is this needed**

Currently the labelsForPV applies to all PVs provisioned by an instance of the local static provisioner.
I would like to be able to add different labels to PVs provisioned via the local static provisioner inside a same StorageClass without having to run multiple instances of the local static provisioner.

**Describe the solution you'd like in detail**

Being able to specify the labelsForPV inside the storageClassMap array for each mapping would solve this.

**Describe alternatives you've considered**

It is possible to deploy multiple local static provisioners and each have their labelsForPV set to a different value but this quickly becomes unpractical.

**Additional context**

An example of what the storageClassMap could look like:
```
  storageClassMap: |
    my-wonderful-sc:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      namePattern: sata-disk-*
      labelsForPV:
        diskType: "sata"
    my-wonderful-sc:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      namePattern: nvme-disk-*
      labelsForPV:
        diskType: "nvme"
```

**Comment by msau42** [comment]
/kind feature
/help

Makes sense to me

**Comment by St0rmingBr4in** [comment]
I will try to work on implementing that.

**Comment by St0rmingBr4in** [comment]
I think adding the associated storageClass name inside the MountConfig struct would the best way of doing this.
This would be the most retro compatible way of implementing this I think.
Basically we could have:

```
storageClassMap:
    sataconfig:
      storageClass: my-wonderful-storageclass # New field
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      namePattern: sata-disk-*
      labelsForPV:  # New field
        diskType: "sata" 
    nvmeconfig:
      storageClass: my-wonderful-storageclass # New field
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      namePattern: nvme-disk-*
      labelsForPV: # New field
        diskType: "nvme"
    my-other-wonderful-storageclass: # If storageClass is undefined the current behavior is unchanged
      hostDir: /mnt/disks
      mountDir: /mnt/disks
```
