### ISSUE TITLE
PV missing

### ISSUE THREAD

**Issue by robertodirienzo** [kubernetes-sigs/sig-storage-local-static-provisioner#327]
First of all thanks for your job!

The problem is:   the provisioner does not create the PV.
I'm using GKE and I am working on 3 pools but I want to create the PVC only in the node belonging to a pool.

The template is:

```
---
# Source: provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-disk-provisioner
  namespace: workflows
  labels:
    helm.sh/chart: provisioner-2.6.0-alpha.1
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-disk-provisioner
---
# Source: provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-disk-provisioner-config
  namespace: workflows
  labels:
    helm.sh/chart: provisioner-2.6.0-alpha.1
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-disk-provisioner
data:
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks/ssd0
      mountDir: /mnt/disks/ssd0
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"
---
# Source: provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  labels:
    helm.sh/chart: provisioner-2.6.0-alpha.1
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-disk-provisioner
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
# Source: provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-disk-provisioner-node-clusterrole
  labels:
    helm.sh/chart: provisioner-2.6.0-alpha.1
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-disk-provisioner
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
# Source: provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-disk-provisioner-node-binding
  labels:
    helm.sh/chart: provisioner-2.6.0-alpha.1
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-disk-provisioner
subjects:
- kind: ServiceAccount
  name: local-disk-provisioner
  namespace: workflows
roleRef:
  kind: ClusterRole
  name: local-disk-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
  
---
# Source: provisioner/templates/daemonset_linux.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-disk-provisioner
  namespace: workflows
  labels:
    helm.sh/chart: provisioner-2.6.0-alpha.1
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-disk-provisioner
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: provisioner
      app.kubernetes.io/instance: local-disk-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: provisioner
        app.kubernetes.io/instance: local-disk-provisioner
      annotations:
        checksum/config: f54dae0e29d0156610668fa10f2c88b202cf2d3467f7c02542be89588388d4f6
    spec:
      serviceAccountName: local-disk-provisioner
      nodeSelector:
        kubernetes.io/os: linux

        cloud.google.com/gke-nodepool: workflows
      tolerations:

        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Equal
          value: present
      affinity:

        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-gpu
                operator: Exists
      containers:
        - name: provisioner
          image: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: local-storage
              mountPath: /mnt/disks/ssd0
              mountPropagation: HostToContainer
      volumes:
        - name: provisioner-config
          configMap:
            name: local-disk-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: local-storage
          hostPath:
            path: /mnt/disks/ssd0  

```

the result is that the PV is not created.

Thanks for your help.
