### ISSUE TITLE
v2.5.0 Release breaks helm chart, version, etc. and provides v2.4.0 application

### ISSUE THREAD

**Issue by thpang** [kubernetes-sigs/sig-storage-local-static-provisioner#361]
**What happened**:

Requested v2.5.0 release of the software via your helm charts. What I actually found I am getting were the following items:

Chart being pulled when requesting v2.5.0:

```yaml
apiVersion: v1
name: provisioner
description: local provisioner chart
keywords:
- storage
- local

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.6.0-alpha.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 2.4.0
```
This does not match the code base at master, which also seems to change the versioning of the helm charts and breaks things as well. The chart version is now 1.0 and does not match the app version. If this is going to be the pattern moving forward that's fine, but please doc these changes. Here is what's provided on the current master branch:

```yaml
apiVersion: v2
name: local-volume-static-provisioner
description: Helm chart for the SIG Storage Local Volume Static Provisioner.
type: application
version: 1.0.0
appVersion: 2.5.0
keywords:
  - storage
  - local
  - volume
home: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/
icon: https://avatars.githubusercontent.com/u/36015203?s=200&v=4
sources:
  - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/
```

**What you expected to happen**:

I would expect to pull a helm chart and code base for v2.5.0 not 2.6.0-alpha. Here is what's pulled when requesting v2.4.0:

```yaml
apiVersion: v1
name: provisioner
description: local provisioner chart
keywords:
- storage
- local

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.4.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 2.4.0
```
Here you can see the version and app version line up and pulls what's expected.

**How to reproduce it**:

```bash
git clone https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner.git
cd sig-storage-local-static-provisioner
git checkout v2.5.0
cat helm/provisioner/Chart.yaml
```

The contents there are incorrect.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
