### ISSUE TITLE
node-cleanup deleter process repeatedly deleting unused, but valid PVs

### ISSUE THREAD

**Issue by scole-scea** [kubernetes-sigs/sig-storage-local-static-provisioner#434]
**What happened**:

In a cluster where the node name != kubernetes.io/hostname, the checker for node deletion often (but not always) thinks new PVs belong to deleted nodes, and deletes them. (Then the provisioner reprovisions them a few seconds later, causing constant churn.) Thankfully this only happens to unused volumes.

**What you expected to happen**:

I expect provisioned, valid PVs to be ignored by the deleter, even if they're not used.

**How to reproduce it**:

In a cluster where node name != kubernetes.io/hostname, launch the storage provisioner and add the node-cleanup service. Notice churn in the volumes.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: `v2.6.0`
- Kubernetes version (use `kubectl version`): `v1.24.17-eks-5e0fdde`
- OS (e.g. from /etc/os-release): Amazon Linux version 2
- Kernel (e.g. `uname -a`): `5.10.201-191.748.amzn2.x86_64`
- Install tools: helm
- Others:

**Comment by niranjandarshann** [comment]
@scole-scea  I had also faced this problem but overcome up with using consistent labelling of the nodes. Ensure that the kubernetes.io/hostname label matches the name of the node  by setting it  on each node correctly. We can achieve this using an init container to set the label.

**Comment by niranjandarshann** [comment]
Here are the Daemonset.yaml  under 
```
spec: 
   initContainers:
      - name: set-node-label
        image: busybox
        command:
        - sh
        - -c
        - |
          NODE_NAME=$(cat /etc/hostname)
          kubectl label node $NODE_NAME kubernetes.io/hostname=$NODE_NAME --overwrite
```
