### ISSUE TITLE
custom SecurityContextConstraint to run sig-storage/local-volume-provisioner in a DaemonSet?

### ISSUE THREAD

**Issue by jonasbartho** [kubernetes-sigs/sig-storage-local-static-provisioner#447]
Hi,

Is there any documentation on which custom SecurityContextConstraint that can be used to run `registry.k8s.io/sig-storage/local-volume-provisioner` in a daemonset without having "privileged=true" enabled? This is not allowed anymore in OKD/Openshift.

Proper documentation around this would be very useful. (using an operator is not possible here btw)

**Comment by jonasbartho** [comment]
I am using the following scc which looks to be working for now:

`scc.yaml`:
```
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
  - CHOWN
  - FSETID
  - SETGID
  - SETUID
  - NET_BIND_SERVICE
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  name: scc-local-provisioner
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - DAC_OVERRIDE
  - FOWNER
  - SETPCAP
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- runtime/default
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - projected
  - secret
```
`clusterrole.yaml`:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:scc-local-provisioner
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - scc-local-provisioner
  resources:
  - securitycontextconstraints
  verbs:
  - use
```
`rolebinding_scc.yaml`:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:scc-local-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:scc-local-provisioner
subjects:
  - kind: ServiceAccount
    name: local-static-provisioner
    namespace: kube-system

```
