### ISSUE TITLE
PersistentVolume naming

### ISSUE THREAD

**Issue by predakanga** [kubernetes-sigs/sig-storage-local-static-provisioner#52]
To simplify administration, it would be helpful to have a friendly name embedded in the generated PV's name.

This could be accomplished by adding the mount point/device name before the checksum.

For example, the following PV:
```Name:              local-pv-27f18fc5
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: local-volume-provisioner-dev-b7cb269c-21f6-11e9-8d64-000c291c888b
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      hdd
Status:            Available
Claim:
Reclaim Policy:    Retain
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          19Gi
Node Affinity:
  Required Terms:
    Term 0:        kubernetes.io/hostname in [dev]
Message:
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /mnt/disks/gitlab
Events:    <none>
```

would become `local-pv-gitlab-27f18fc5`

This shouldn't cause any problems, as the name is already used to generate the checksum - any changes in filename would already cause a change in PV name.

**Comment by cofyc** [comment]
I agree current naming is not friendly for managing PVs. However, PV name is currently used as a unique identifier for the path on the node. And the more flexible way to help PV administration is to add labels, e.g.

```
- local.storage.k8s.io/hostname = <node-name>
- local.storage.k8s.io/storageclass = <storage-class-name>
```

Additionally, provisioner configuration can support extra labels for discovered PVs for each storage class, e.g.

```
local-storage-gitlab:
  hostDir: /mnt/disks/gitlab
  mountDir: /mnt/disks/gitlab
  labels:
     app=gitlab
local-storage-other:
  hostDir: /mnt/disks/other
  mountDir: /mnt/disks/other
  labels:
     app=other
```

Then, you can run `kubectl get pv -l app=gitlab` to list all gitlab PVs.

What do you think? cc @msau42

**Comment by msau42** [comment]
I like the labels idea. We also originally went with the hashing approach because we didn't want to potentially leak sensitive information into the PV name which may be readable globally

**Comment by KevinTHU** [comment]
now the node information of pv can only be shown in the **annotation** or **Node Affinity**, I don't think it is a friendly way (at least the info could be searched, like label, or the best directly on pv name), hope for consideration.

**Comment by cofyc** [comment]
For now, if you want to search PVs by node name, you can configure `kubernetes.io/hostname` in `nodeLabelsForPV`, local-volume-provisioner will copy node labels to PVs it provisioned.

For example:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: kube-system
data:
  nodeLabelsForPV: |
    - kubernetes.io/hostname
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
```

Update config map and restart local-volume-provisioner:

```
kubectl -n kube-system delete pods -lapp=local-volume-provisioner
```

Check new PVs it provisioned: (local-volume-provisioner does not sync labels between node and PVs. It only applies to new PVs for now)

```
$ kubectl -n kube-system get pv -l kubernetes.io/hostname=kube-node-3
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS    REASON   AGE
local-pv-d20c2706   6Gi        RWO            Delete           Available           local-storage            5m4s
```
