### ISSUE TITLE
Cleanup Job fails

### ISSUE THREAD

**Issue by Lavaburn** [kubernetes-sigs/sig-storage-local-static-provisioner#55]
The cleanup job of block devices returns error "/mnt/kubernetes/vol_10g_b is not a block device.", and PV remains stuck in "Released" state.

Error is triggered by validateBlockDevice function in the cleanup pod (local-volume-provisioner:v2.3.0).
This pod is correctly mounting /mnt/kubernetes (mountPath), but not mounting /dev, hence the symlinks are invalid.

Creating and using the local volumes works, because local-volume-provisioner job does mount /dev.

```
kubectl get jobs -n kube-system cleanup-local-pv-4579e45f -o yaml
apiVersion: batch/v1
kind: Job
-- snip -- 
  name: cleanup-local-pv-4579e45f
  namespace: kube-system
-- snip -- 
      containers:
      - command:
        - /scripts/quick_reset.sh
        env:
        - name: LOCAL_PV_BLKDEVICE
          value: /mnt/kubernetes/vol_10g_b
        image: quay.io/external_storage/local-volume-provisioner:v2.3.0
        imagePullPolicy: IfNotPresent
        name: cleaner
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/kubernetes
          name: mount-25626bfb
  -- snip -- 
      volumes:
      - hostPath:
          path: /mnt/kubernetes
          type: ""
        name: mount-25626bfb
-- snip -- 
```

```
kubectl get pods -n kube-system local-volume-provisioner-pjwsg -o yaml
apiVersion: v1
kind: Pod
-- snip -- 
  name: local-volume-provisioner-pjwsg
  namespace: kube-system
-- snip -- 
    image: quay.io/external_storage/local-volume-provisioner:v2.3.0
    imagePullPolicy: IfNotPresent
    name: provisioner
-- snip -- 
    securityContext:
      privileged: true
      procMount: Default
-- snip -- 
    volumeMounts:
    - mountPath: /etc/provisioner/config
      name: provisioner-config
      readOnly: true
    - mountPath: /dev
      name: provisioner-dev
    - mountPath: /mnt/kubernetes
      mountPropagation: HostToContainer
      name: local-disks
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: local-storage-admin-token-wwp9b
      readOnly: true
-- snip -- 
  volumes:
  - configMap:
      defaultMode: 420
      name: local-provisioner-config
    name: provisioner-config
  - hostPath:
      path: /dev
      type: ""
    name: provisioner-dev
  - hostPath:
      path: /mnt/kubernetes
      type: ""
    name: local-disks
  - name: local-storage-admin-token-wwp9b
    secret:
      defaultMode: 420
      secretName: local-storage-admin-token-wwp9b
-- snip -- 
```
