### ISSUE TITLE
Could not get node information

### ISSUE THREAD

**Issue by scphantm** [kubernetes-sigs/sig-storage-local-static-provisioner#58]
I am struggling to get this running.  Im following these instructions

https://docs.openshift.com/container-platform/3.11/install_config/configuring_local.html

I got everything done, but when the pod attempts to start, i get this error.

`F0312 02:19:33.183835       1 main.go:115] Could not get node information: nodes "okdtest.panasas.com" is forbidden: User "system:serviceaccount:default:panfs-storage-admin" cannot get nodes at the cluster scope: no RBAC policy matched`

what am i missing?

**Comment by msau42** [comment]
/assign @gnufied 
for openshift configuration

**Comment by gnufied** [comment]
Did you install provisioner using openshift provided template?  https://raw.githubusercontent.com/openshift/origin/release-3.11/examples/storage-examples/local-examples/local-storage-provisioner-template.yaml 

If you did - it creates a `ClusterRoleBinding` that binds service account being used with local storage provisioner to `system:node` `ClusterRole`. That role binding should be enough to give access to service account.

**Comment by scphantm** [comment]
yes.  for my company, we have to replace `local` with `panfs`, but here's my template

```

apiVersion: v1
kind: Template
metadata:
  name: "panfs-storage-provisioner"
objects:

# $SERVICE_ACCOUNT must be able to manipulate with PVs
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: panfs-storage:provisioner-pv-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:persistent-volume-provisioner
  subjects:
  - kind: ServiceAccount
    name: ${SERVICE_ACCOUNT}
    namespace: ${NAMESPACE}

# $SERVICE_ACCOUNT must be able to list nodes
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: panfs-storage:provisioner-node-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:node
  subjects:
  - kind: ServiceAccount
    name: ${SERVICE_ACCOUNT}
    namespace: ${NAMESPACE}

# DaemonSet with provisioners
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: panfs-volume-provisioner
  spec:
    template:
      metadata:
        labels:
          app: panfs-volume-provisioner
      spec:
        containers:
        - env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: VOLUME_CONFIG_NAME
            value: ${CONFIGMAP}
          image: ${PROVISIONER_IMAGE}
          name: provisioner
          securityContext:
            runAsUser: 0
            seLinuxOptions:
              # Trump SELinux contexts of all pods that could write files to panfs volume - the provisioner must be able to clean their files.
              level: "s0:c0.c1023"
          volumeMounts:
          - mountPath: /mnt/panfs-kube
            name: panfs-storage
            mountPropagation: HostToContainer
          - mountPath: /etc/provisioner/config
            name: provisioner-config
            readOnly: true
        serviceAccountName: "${SERVICE_ACCOUNT}"
        volumes:
        - hostPath:
            path: /mnt/panfs-kube
          name: panfs-storage
        - configMap:
            name: ${CONFIGMAP}
          name: provisioner-config

parameters:
  - name: SERVICE_ACCOUNT
    description: Name of service account that is able to run pods as root and use HostPath volumes.
    required: true
    value: panfs-storage-admin
  - name: NAMESPACE
    description: Name of namespace where panfs provisioners run
    required: true
    value: panfs-storage
  - name: CONFIGMAP
    description: Name of ConfigMap with panfs provisioner configuration.
    required: true
    value: panfs-storage-admin
  - name: PROVISIONER_IMAGE
    description: Name of image with panfs provisioner.
    required: true
    value: quay.io/external_storage/local-volume-provisioner:v1.0.1

```

and my new-app command

```
    oc new-app \
    -p CONFIGMAP=panfs-volume-config \
    -p SERVICE_ACCOUNT=panfs-storage-admin \
    -p NAMESPACE=panfs-storage \
    -p PROVISIONER_IMAGE=quay.io/external_storage/local-volume-provisioner:v2.3.0 \
    panfs-storage-provisioner
```
