### ISSUE TITLE
Path "/mnt/disks/by-uuid" is not an actual mountpoint

### ISSUE THREAD

**Issue by derekperkins** [kubernetes-sigs/sig-storage-local-static-provisioner#68]
I just ran this on a new GKE cluster (1.12.5-gke.5 without RBAC) and while it appears that the PVs are all created correctly, each pod logs out an error every 10 seconds saying that `Path "/mnt/disks/by-uuid" is not an actual mountpoint`. Is that something I need to be worried about causing data integrity problems?

It feels like it's probably iterating the `by-uuid` directory to get the disks, but not excluding the parent directory from the iteration.

### logs on all DaemonSet pods
```
common.go:316] StorageClass "local-scsi" configured with MountDir "/mnt/disks", HostDir "/mnt/disks", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
main.go:60] Loaded configuration: {StorageClassConfig:map[local-scsi:{HostDir:/mnt/disks MountDir:/mnt/disks BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:}] NodeLabelsForPV:[] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:true}
main.go:61] Ready to run...
common.go:378] Creating client using in-cluster config
main.go:82] Starting controller
main.go:96] Starting metrics server at :8080
controller.go:45] Initializing volume cache
cache.go:55] Added pv "local-pv-a1e255f1" to cache
cache.go:55] Added pv "local-pv-18439af4" to cache
cache.go:55] Added pv "local-pv-df57f635" to cache
cache.go:55] Added pv "local-pv-6384a96b" to cache
cache.go:55] Added pv "local-pv-1e0913d8" to cache
cache.go:55] Added pv "local-pv-709ace0e" to cache
cache.go:55] Added pv "local-pv-2d4262cf" to cache
cache.go:55] Added pv "local-pv-d216f352" to cache
controller.go:108] Controller started
discovery.go:269] Path "/mnt/disks/by-uuid" is not an actual mountpoint
discovery.go:269] Path "/mnt/disks/by-uuid" is not an actual mountpoint
...
---
(repeats every 10 seconds forever)
discovery.go:269] Path "/mnt/disks/by-uuid" is not an actual mountpoint
---

---
(repeats every 10 minutes forever)
cache.go:64] Updated pv "local-pv-a1e255f1" to cache
cache.go:64] Updated pv "local-pv-1e0913d8" to cache
cache.go:64] Updated pv "local-pv-709ace0e" to cache
cache.go:64] Updated pv "local-pv-18439af4" to cache
cache.go:64] Updated pv "local-pv-df57f635" to cache
cache.go:64] Updated pv "local-pv-2d4262cf" to cache
cache.go:64] Updated pv "local-pv-d216f352" to cache
cache.go:64] Updated pv "local-pv-6384a96b" to cache
---
```

### helm generated yaml
```
---
# Source: provisioner/templates/provisioner.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: local-volume-provisioner
  labels:
    heritage: "Tiller"
    release: "release-name"
    chart: provisioner-2.3.0
data:
  useNodeNameOnly: "true"
  storageClassMap: |
    local-scsi:
       hostDir: /mnt/disks
       mountDir: /mnt/disks
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: local-volume-provisioner
  labels:
    app: local-volume-provisioner
    heritage: "Tiller"
    release: "release-name"
    chart: provisioner-2.3.0
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-storage-admin
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      tolerations:
        - operator: Exists
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:v2.3.0"
          name: provisioner
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: "quay.io/external_storage/local-volume-provisioner:v2.3.0"
          volumeMounts:
            - mountPath: /etc/provisioner/config
              name: provisioner-config
              readOnly: true
            - mountPath: /dev
              name: provisioner-dev
            - mountPath: /mnt/disks
              name: local-scsi
              mountPropagation: "HostToContainer"
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: local-scsi
          hostPath:
            path: /mnt/disks
```

**Comment by msau42** [comment]
Sorry for the confusion, if you're using the GKE with the nvme whitelisted option, you should use this deployment file for the provisioner:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/helm/generated_examples/gce.yaml

This deployment uses the /mnt/disks/by-uuid paths instead of /mnt/disks.

The main difference is that the mount points under /mnt/disks are not unique across nodes (including node recreations), whereas the "by-uuid" mount points use unique names.  Using unique names avoids the issue where if your node gets recreated, the disks come back with the same name so the mount will succeed, but all the data is gone.

**Comment by derekperkins** [comment]
I didn't enable nvme on this node pool or cluster. Should I still use a different `hostDir`?

**Comment by msau42** [comment]
If you want the disks to be uniquely named so that your Pods don't automatically get mounted with blank disks on a node repair/upgrade, then you should use: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/helm/generated_examples/gce.yaml

Otherwise, the existing deployment is sufficient.

Some more background on the issue: https://github.com/kubernetes-incubator/external-storage/issues/1001#issuecomment-424047424

**Comment by derekperkins** [comment]
Ok, sounds good. I'll go ahead and use that config you're referencing. Thanks!

**Comment by derekperkins** [comment]
I deleted all my PVs and deployed that configuration, but it isn't detecting any of the local disks or creating new PVs. It is definitely running on nodes with local ssds.

**Comment by derekperkins** [comment]
The only changes I made to the file were to use a different namespace and add these:

```
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"

      tolerations:
        - operator: "Exists"
```
